---
- name: Include prerequisite tasks
  include_tasks: prerequisites.yml

- name: Include K3s agent installation tasks
  include_tasks: k3s-agent.yml

- name: Include systemd service tasks
  include_tasks: systemd.yml

