---
- name: Install Podman and dependencies
  apt:
    name:
      - podman
      - podman-compose
      - fuse-overlayfs
      - aardvark-dns
    state: present
    update_cache: yes

- name: Create compose directory
  file:
    path: /opt/podman-compose
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy compose.yml
  copy:
    src: compose.yml
    dest: /opt/podman-compose/compose.yml
    owner: root
    group: root
    mode: '0644'

- name: Create IPv6-only Podman network
  containers.podman.podman_network:
    name: psuite-network
    state: present
    ipv6: true
    subnet: "fd00:db8:1::/64"
    gateway: "fd00:db8:1::1"


- name: Start services with podman-compose
  command: podman-compose up -d
  args:
    chdir: /opt/podman-compose
