$ANSIBLE_VAULT;1.1;AES256
35363633656534396339343930323238363631636637316231313035613437613533326338613738
3366313565363938303062646663643231306537383536300a336430383830313364316131613937
61616266633965396562383339666361663262383136633233636364353533653436623735303763
3035393136343863360a663935393662356236336132353837626365343962306334316232376466
35306139626362393564323932386337306365636235333861316563316162373432663865623866
62623739376532646237343961353061393731366165303132303131666435316464613435613161
61366534306361386365356139643131616334653234383233393635323761653964363261343334
38393365343433613262306364333237343132626366343133383135303139653130356163363562
37663065666230626462363438326435383833393332313561623066366432396331646530663261
61326231336362653861633932396430653033356634633463353938366662666532363139396566
64376130356137303438393961343638396133343761353632316161366332343139323132366331
39343438393131623030626239623562633064333132323761623339656565363338303361626462
63626431383932326231646261373739313162396662306435663935323064386339303937393664
35613462663662376362343263333332656461323437373834626435643061666665613832356338
31626230626363643339353831313663633365336164313563383130336234373236613432326230
32383963636137313537333066313930343136336261613535663763616563373135626563313166
63653436373564643834366530313636646366646363333638313131316633303034326266373835
35653333353432313833373633636338343663336632363066313437383637373761626164383331
62373031363130656232333064343461663236376439393164623965316530623837646134353762
63363965336334396533
