---
- name: Include prerequisite tasks
  include_tasks: prerequisites.yml

- name: Include K3s installation tasks
  include_tasks: k3s.yml

- name: Include systemd service tasks
  include_tasks: systemd.yml
