---
openclaw_user: "openclaw"
openclaw_group: "openclaw"
openclaw_service_name: "openclaw-gateway"

openclaw_authorized_keys:
  - "{{ lookup('file', ansible_ssh_private_key_file + '.pub') }}"

nodejs_version: "22.x"
openclaw_npm_name: "openclaw"
openclaw_npm_version: "latest"
openclaw_force_reinstall: false

openclaw_npm_env:
  NPM_CONFIG_JOBS: "1"
  NPM_CONFIG_PROGRESS: "false"
  NPM_CONFIG_AUDIT: "false"
  NPM_CONFIG_FUND: "false"
  NPM_CONFIG_LOGLEVEL: "warn"

openclaw_dashboard_host: "127.0.0.1"
openclaw_dashboard_port: 18789
openclaw_nginx_listen_port: 80
openclaw_nginx_server_name: "openclaw.cosmos.cboxlab.com"
