---
openclaw_user: "openclaw"
openclaw_group: "openclaw"
openclaw_service_name: "openclaw"

openclaw_authorized_keys:
  - "{{ lookup('file', ansible_ssh_private_key_file + '.pub') }}"

nodejs_version: "22.x"
openclaw_npm_package: "openclaw@latest"
